import { useQuery } from "@tanstack/solid-query";
import { useNavigate } from "@tanstack/solid-router";
import { createEffect, createMemo, createSignal, For, on, Show, untrack } from "solid-js";
import IconTriangleLeft from "~icons/ph/caret-left-fill";
import IconTriangleRight from "~icons/ph/caret-right-fill";

import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import type { MenuItem } from "~/components/menu";
import Menu from "~/components/menu";
import MarkGlyph from "~/components/tic-tac-toe/mark-glyph";
import TitleBar from "~/components/title-bar";
import Avatar from "~/components/ui/avatar";
import MenuRow from "~/components/ui/menu-row";
import SlantPanel from "~/components/ui/slant-panel";
import { useNavigation } from "~/hooks/navigation";
import { t } from "~/lib/i18n";
import { lobbyQueryOptions } from "~/lib/queries";
import { notify } from "~/lib/toast";
import type { User } from "~/lib/types";
import { getColorVar } from "~/lib/utils/color";
import { lobbyStore } from "~/stores/lobby";
import {
  DEFAULT_GRID_SIZE,
  defaultWinLength,
  GRID_SIZES,
  type Mark,
  type SingerMode,
  type Team,
  ticTacToeStore,
  winLengthOptions,
} from "~/stores/party/tic-tac-toe";
import { settingsStore } from "~/stores/settings";
import { songsStore } from "~/stores/songs";

type Assignment = Mark | "none";

// Columns in visual order: Team X | Unassigned | Team O.
const ASSIGNMENT_COLUMNS: { value: Assignment; mark: Mark | null }[] = [
  { value: "x", mark: "x" },
  { value: "none", mark: null },
  { value: "o", mark: "o" },
];

// Cycle order matches the column layout so left/right moves through the same sequence.
const ASSIGNMENT_ORDER: Assignment[] = ASSIGNMENT_COLUMNS.map((column) => column.value);

const assignmentLabel = (value: Assignment): string =>
  value === "x"
    ? t("party.ticTacToe.teamX")
    : value === "o"
      ? t("party.ticTacToe.teamO")
      : t("party.ticTacToe.unassigned");

export default function TicTacToeSettingsScreen() {
  const navigate = useNavigate();
  const onBack = () => navigate({ to: "/party" });

  const lobbyQuery = useQuery(() => lobbyQueryOptions());

  const users = createMemo<User[]>(() => [...(lobbyQuery.data?.users ?? []), ...lobbyStore.localPlayersInLobby()]);

  const [assignments, setAssignments] = createSignal<Record<User["id"], Assignment>>({});
  const [gridSize, setGridSize] = createSignal(DEFAULT_GRID_SIZE);
  const [winLength, setWinLength] = createSignal(defaultWinLength(DEFAULT_GRID_SIZE));
  const [singerMode, setSingerMode] = createSignal<SingerMode>("random");

  // When the grid size changes, move the win length to that grid's default (still changeable after).
  createEffect(
    on(
      gridSize,
      (size) => {
        setWinLength(defaultWinLength(size));
      },
      { defer: true },
    ),
  );

  const getAssignment = (user: User): Assignment => assignments()[user.id] ?? "none";

  const setAssignment = (user: User, assignment: Assignment) => {
    setAssignments((prev) => ({ ...prev, [user.id]: assignment }));
  };

  const cycleAssignment = (user: User, direction: "left" | "right") => {
    const current = getAssignment(user);
    const currentIndex = ASSIGNMENT_ORDER.indexOf(current);
    const length = ASSIGNMENT_ORDER.length;
    const nextIndex = direction === "right" ? (currentIndex + 1) % length : (currentIndex - 1 + length) % length;
    setAssignment(user, ASSIGNMENT_ORDER[nextIndex] ?? "none");
  };

  const teamColor = (mark: Mark) => {
    const index = mark === "x" ? 0 : 1;
    return settingsStore.microphones()[index]?.color ?? (mark === "x" ? "sky" : "red");
  };

  const startGame = () => {
    if (users().length < 2) {
      notify({ message: t("party.ticTacToe.notEnoughPlayers"), intent: "error" });
      return;
    }

    const microphones = settingsStore.microphones();
    if (microphones.length < 2) {
      notify({ message: t("party.ticTacToe.microphoneRequired"), intent: "error" });
      return;
    }

    const teamXPlayers = users().filter((user) => getAssignment(user) === "x");
    const teamOPlayers = users().filter((user) => getAssignment(user) === "o");

    if (teamXPlayers.length === 0 || teamOPlayers.length === 0) {
      notify({ message: t("party.ticTacToe.teamNeedsPlayer"), intent: "error" });
      return;
    }

    const songs = songsStore.songs().filter((song) => song.voices.length === 1);
    if (songs.length === 0) {
      notify({ message: t("party.ticTacToe.noSongs"), intent: "error" });
      return;
    }

    // `order` is (re)generated by startGame; an empty placeholder keeps the type satisfied.
    const teams: [Team, Team] = [
      { mark: "x", players: teamXPlayers, order: [], rotationIndex: 0 },
      { mark: "o", players: teamOPlayers, order: [], rotationIndex: 0 },
    ];

    ticTacToeStore.startGame(teams, songs, gridSize(), winLength(), singerMode());
    navigate({ to: "/party/tic-tac-toe" });
  };

  const teamSize = (assignment: Assignment) => users().filter((user) => getAssignment(user) === assignment).length;

  // A round already in progress: only offer continuing it or restarting (which clears it and reopens the options).
  // Decided on entry and after a restart, not live: starting sets `playing`, which would otherwise swap the
  // menu to Continue/Restart while this page is still transitioning out.
  const [resuming, setResuming] = createSignal(untrack(() => ticTacToeStore.state().playing));

  const menuItems = (): MenuItem[] => {
    if (resuming()) {
      return [
        {
          type: "button",
          label: t("party.ticTacToe.continue"),
          action: () => navigate({ to: "/party/tic-tac-toe" }),
        },
        {
          type: "button",
          label: t("party.ticTacToe.restart"),
          action: () => {
            ticTacToeStore.reset();
            setResuming(false);
          },
        },
      ];
    }

    return [
      {
        type: "select-number",
        label: t("party.ticTacToe.gridSize"),
        value: () => gridSize(),
        options: [...GRID_SIZES],
        onChange: (value) => setGridSize(value),
        renderValue: (value) => <span>{value !== null ? `${value} x ${value}` : "?"}</span>,
      },
      {
        type: "select-number",
        label: t("party.ticTacToe.winLength"),
        value: () => winLength(),
        options: winLengthOptions(gridSize()),
        onChange: (value) => setWinLength(value),
        renderValue: (value) => <span>{value !== null ? String(value) : "?"}</span>,
      },
      {
        type: "select-string",
        label: t("party.ticTacToe.singerSelection"),
        value: () => singerMode(),
        options: ["random", "manual"],
        onChange: (value) => setSingerMode(value as SingerMode),
        renderValue: (value) => (
          <span>{value === "manual" ? t("party.ticTacToe.singerManual") : t("party.ticTacToe.singerRandom")}</span>
        ),
      },
      ...users().map((user): MenuItem => ({
        type: "custom",
        interactive: true,
        render: (ctx) => (
          <TeamAssignmentRow
            user={user}
            assignment={getAssignment(user)}
            selected={ctx.selected()}
            gradient={ctx.gradient()}
            teamColor={teamColor}
            teamSize={teamSize}
            onCycle={(direction) => cycleAssignment(user, direction)}
            onSelect={(assignment) => setAssignment(user, assignment)}
          />
        ),
      })),
      {
        type: "button",
        label: t("party.ticTacToe.start"),
        action: startGame,
      },
    ];
  };

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title={t("party.ticTacToe.title")} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <Menu items={menuItems()} onBack={onBack} gradient="gradient-party" />
    </Layout>
  );
}

interface TeamAssignmentRowProps {
  user: User;
  assignment: Assignment;
  selected: boolean;
  gradient: string;
  teamColor: (mark: Mark) => string;
  teamSize: (assignment: Assignment) => number;
  onCycle: (direction: "left" | "right") => void;
  onSelect: (assignment: Assignment) => void;
}

/** A player's row: the player on the left, a slanted X · Unassigned · O switch on the right. */
function TeamAssignmentRow(props: TeamAssignmentRowProps) {
  // Only left/right cycle the team; up/down stay with the Menu to move between players.
  useNavigation(() => ({
    enabled: props.selected,
    onKeydown(event) {
      if (event.action === "left") props.onCycle("left");
      else if (event.action === "right") props.onCycle("right");
    },
  }));

  return (
    <MenuRow
      selected={props.selected}
      gradient={props.gradient}
      label={
        <span class="flex min-w-0 items-center gap-3">
          <Avatar user={props.user} class="size-8 shrink-0" />
          <span class="truncate">{props.user.username ?? "?"}</span>
        </span>
      }
    >
      <div class="flex w-full items-center gap-4">
        <button type="button" class="cursor-pointer text-2xl" onClick={() => props.onCycle("left")}>
          <IconTriangleLeft />
        </button>
        <div class="grid grow grid-cols-3 gap-1.5">
          <For each={ASSIGNMENT_COLUMNS}>
            {(column) => {
              const active = () => props.assignment === column.value;
              return (
                <SlantPanel
                  as="button"
                  type="button"
                  class="flex h-10 min-w-0 cursor-pointer items-center justify-center gap-2 px-2 text-sm font-bold transition-opacity"
                  classList={{ "opacity-50 hover:opacity-80": !active() }}
                  surface="rounded-md transition-colors"
                  surfaceClassList={{
                    "bg-black/25": !active(),
                    "bg-white/20 ring-1 ring-white/40 ring-inset": active() && !column.mark,
                    "shadow-[0.25cqw_0.25cqw_0_rgb(0_0_0/0.35)]": active(),
                  }}
                  surfaceStyle={
                    active() && column.mark
                      ? {
                          background: `linear-gradient(90deg, ${getColorVar(props.teamColor(column.mark), 500)}, ${getColorVar(props.teamColor(column.mark), 700)})`,
                        }
                      : undefined
                  }
                  onClick={() => props.onSelect(column.value)}
                >
                  <Show when={column.mark}>
                    {(mark) => (
                      <MarkGlyph mark={mark()} color={props.teamColor(mark())} class="size-[1.6cqw] shrink-0" />
                    )}
                  </Show>
                  <span class="truncate">{assignmentLabel(column.value)}</span>
                  {/* Always shown (faded at 0), so the label never shifts when a team gets its first player */}
                  <Show when={column.mark}>
                    <span
                      class="rounded-sm bg-black/25 px-1.5 text-xs tabular-nums transition-opacity"
                      classList={{ "opacity-40": props.teamSize(column.value) === 0 }}
                    >
                      {props.teamSize(column.value)}
                    </span>
                  </Show>
                </SlantPanel>
              );
            }}
          </For>
        </div>
        <button type="button" class="cursor-pointer text-2xl" onClick={() => props.onCycle("right")}>
          <IconTriangleRight />
        </button>
      </div>
    </MenuRow>
  );
}
