services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    environment:
      VITE_APP_URL: https://app.tuneperfect.localhost
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    ports:
      - 3001:3000
    environment:
      VITE_API_URL: https://api.tuneperfect.localhost
