import { useQuery } from "@tanstack/solid-query";
import { createFileRoute, useNavigate } from "@tanstack/solid-router";
import { createEffect, createMemo, createSignal, For, on, Show } from "solid-js";
import IconCircle from "~icons/lucide/circle";
import IconX from "~icons/lucide/x";
import IconTriangleLeft from "~icons/sing/triangle-left";
import IconTriangleRight from "~icons/sing/triangle-right";

import KeyHints from "~/components/key-hints";
import Layout from "~/components/layout";
import type { MenuItem } from "~/components/menu";
import Menu from "~/components/menu";
import TitleBar from "~/components/title-bar";
import Avatar from "~/components/ui/avatar";
import { useNavigation } from "~/hooks/navigation";
import { t } from "~/lib/i18n";
import { lobbyQueryOptions } from "~/lib/queries";
import { notify } from "~/lib/toast";
import type { User } from "~/lib/types";
import { getColorVar } from "~/lib/utils/color";
import { lobbyStore } from "~/stores/lobby";
import {
  DEFAULT_GRID_SIZE,
  defaultWinLength,
  GRID_SIZES,
  type Mark,
  type SingerMode,
  type Team,
  ticTacToeStore,
  winLengthOptions,
} from "~/stores/party/tic-tac-toe";
import { settingsStore } from "~/stores/settings";
import { songsStore } from "~/stores/songs";

type Assignment = Mark | "none";

// Columns in visual order: Team X | Unassigned | Team O.
const ASSIGNMENT_COLUMNS: { value: Assignment; mark: Mark | null }[] = [
  { value: "x", mark: "x" },
  { value: "none", mark: null },
  { value: "o", mark: "o" },
];

// Cycle order matches the column layout so left/right moves through the same sequence.
const ASSIGNMENT_ORDER: Assignment[] = ASSIGNMENT_COLUMNS.map((column) => column.value);

// Resolved per render so labels stay reactive to locale changes (returns a plain string).
// Team columns show the generic "Team" label since the X/O icon already conveys the mark.
const assignmentLabel = (value: Assignment): string =>
  value === "none" ? t("party.ticTacToe.unassigned") : t("party.ticTacToe.team");

export const Route = createFileRoute("/party/tic-tac-toe/settings")({
  component: TicTacToeSettingsComponent,
  beforeLoad: async ({ context }) => {
    context.queryClient.prefetchQuery(lobbyQueryOptions());
  },
});

function TicTacToeSettingsComponent() {
  const navigate = useNavigate();
  const onBack = () => navigate({ to: "/party" });

  const lobbyQuery = useQuery(() => lobbyQueryOptions());

  const users = createMemo<User[]>(() => [...(lobbyQuery.data?.users ?? []), ...lobbyStore.localPlayersInLobby()]);

  const [assignments, setAssignments] = createSignal<Record<User["id"], Assignment>>({});
  const [gridSize, setGridSize] = createSignal(DEFAULT_GRID_SIZE);
  const [winLength, setWinLength] = createSignal(defaultWinLength(DEFAULT_GRID_SIZE));
  const [singerMode, setSingerMode] = createSignal<SingerMode>("random");

  // When the grid size changes, move the win length to that grid's default (still changeable after).
  createEffect(
    on(
      gridSize,
      (size) => {
        setWinLength(defaultWinLength(size));
      },
      { defer: true },
    ),
  );

  const getAssignment = (user: User): Assignment => assignments()[user.id] ?? "none";

  const setAssignment = (user: User, assignment: Assignment) => {
    setAssignments((prev) => ({ ...prev, [user.id]: assignment }));
  };

  const cycleAssignment = (user: User, direction: "left" | "right") => {
    const current = getAssignment(user);
    const currentIndex = ASSIGNMENT_ORDER.indexOf(current);
    const length = ASSIGNMENT_ORDER.length;
    const nextIndex = direction === "right" ? (currentIndex + 1) % length : (currentIndex - 1 + length) % length;
    setAssignment(user, ASSIGNMENT_ORDER[nextIndex] ?? "none");
  };

  const teamColor = (mark: Mark) => {
    const index = mark === "x" ? 0 : 1;
    return settingsStore.microphones()[index]?.color ?? (mark === "x" ? "blue" : "red");
  };

  const startGame = () => {
    if (users().length < 2) {
      notify({ message: t("party.ticTacToe.notEnoughPlayers"), intent: "error" });
      return;
    }

    const microphones = settingsStore.microphones();
    if (microphones.length < 2) {
      notify({ message: t("party.ticTacToe.microphoneRequired"), intent: "error" });
      return;
    }

    const teamXPlayers = users().filter((user) => getAssignment(user) === "x");
    const teamOPlayers = users().filter((user) => getAssignment(user) === "o");

    if (teamXPlayers.length === 0 || teamOPlayers.length === 0) {
      notify({ message: t("party.ticTacToe.teamNeedsPlayer"), intent: "error" });
      return;
    }

    const songs = songsStore.songs().filter((song) => song.voices.length === 1);
    if (songs.length === 0) {
      notify({ message: t("party.ticTacToe.noSongs"), intent: "error" });
      return;
    }

    // `order` is (re)generated by startGame; an empty placeholder keeps the type satisfied.
    const teams: [Team, Team] = [
      { mark: "x", players: teamXPlayers, order: [], rotationIndex: 0 },
      { mark: "o", players: teamOPlayers, order: [], rotationIndex: 0 },
    ];

    ticTacToeStore.startGame(teams, songs, gridSize(), winLength(), singerMode());
    navigate({ to: "/party/tic-tac-toe" });
  };

  // A round already in progress: only offer continuing it or restarting (which clears it and reopens the options).
  const menuItems = (): MenuItem[] => {
    if (ticTacToeStore.state().playing) {
      return [
        {
          type: "button",
          label: t("party.ticTacToe.continue"),
          action: () => navigate({ to: "/party/tic-tac-toe" }),
        },
        {
          type: "button",
          label: t("party.ticTacToe.restart"),
          action: () => ticTacToeStore.reset(),
        },
      ];
    }

    return [
      {
        type: "select-number",
        label: t("party.ticTacToe.gridSize"),
        value: () => gridSize(),
        options: [...GRID_SIZES],
        onChange: (value) => setGridSize(value),
        renderValue: (value) => <span>{value !== null ? `${value} x ${value}` : "?"}</span>,
      },
      {
        type: "select-number",
        label: t("party.ticTacToe.winLength"),
        value: () => winLength(),
        options: winLengthOptions(gridSize()),
        onChange: (value) => setWinLength(value),
        renderValue: (value) => <span>{value !== null ? String(value) : "?"}</span>,
      },
      {
        type: "select-string",
        label: t("party.ticTacToe.singerSelection"),
        value: () => singerMode(),
        options: ["random", "manual"],
        onChange: (value) => setSingerMode(value as SingerMode),
        renderValue: (value) => (
          <span>{value === "manual" ? t("party.ticTacToe.singerManual") : t("party.ticTacToe.singerRandom")}</span>
        ),
      },
      ...users().map(
        (user): MenuItem => ({
          type: "custom",
          interactive: true,
          render: (ctx) => (
            <TeamAssignmentRow
              user={user}
              assignment={getAssignment(user)}
              selected={ctx.selected()}
              gradient={ctx.gradient()}
              teamColor={teamColor}
              onCycle={(direction) => cycleAssignment(user, direction)}
              onSelect={(assignment) => setAssignment(user, assignment)}
            />
          ),
        }),
      ),
      {
        type: "button",
        label: t("party.ticTacToe.start"),
        action: startGame,
      },
    ];
  };

  return (
    <Layout
      intent="secondary"
      header={<TitleBar title={t("party.ticTacToe.title")} onBack={onBack} />}
      footer={<KeyHints hints={["back", "navigate", "confirm"]} />}
    >
      <Menu items={menuItems()} onBack={onBack} gradient="gradient-party" />
    </Layout>
  );
}

interface TeamAssignmentRowProps {
  user: User;
  assignment: Assignment;
  selected: boolean;
  gradient: string;
  teamColor: (mark: Mark) => string;
  onCycle: (direction: "left" | "right") => void;
  onSelect: (assignment: Assignment) => void;
}

function TeamAssignmentRow(props: TeamAssignmentRowProps) {
  // Only left/right cycle the team; up/down stay with the Menu to move between players.
  useNavigation(() => ({
    enabled: props.selected,
    onKeydown(event) {
      if (event.action === "left") {
        props.onCycle("left");
      } else if (event.action === "right") {
        props.onCycle("right");
      }
    },
  }));

  return (
    <div class="grid h-16 items-center overflow-hidden rounded-lg">
      {/* Gradient background layer, same pattern as Select */}
      <div
        class="col-start-1 row-start-1 h-full w-full bg-linear-to-r transition-opacity"
        classList={{
          [props.gradient]: true,
          "opacity-0": !props.selected,
        }}
      />

      <div class="z-2 col-start-1 row-start-1 mx-auto grid w-full max-w-320 grid-cols-[1fr_3fr] items-center">
        <div class="flex items-center justify-center gap-3 overflow-hidden text-center text-xl font-bold">
          <Avatar user={props.user} class="h-8 w-8 shrink-0" />
          <span class="truncate">{props.user.username ?? "?"}</span>
        </div>

        <div class="flex items-center gap-8">
          <button class="cursor-pointer" type="button" onClick={() => props.onCycle("left")}>
            <IconTriangleLeft />
          </button>
          <div class="grid grow grid-cols-3 gap-2">
            <For each={ASSIGNMENT_COLUMNS}>
              {(column) => {
                const isActive = () => props.assignment === column.value;
                return (
                  <button
                    type="button"
                    class="flex h-10 cursor-pointer items-center justify-center gap-1 rounded-lg font-bold transition-all"
                    classList={{
                      "text-white shadow-md ring-2 ring-white/60": isActive(),
                      "bg-white/15 text-white": isActive() && !column.mark,
                      "bg-black/20 opacity-50 hover:opacity-80": !isActive(),
                    }}
                    style={
                      isActive() && column.mark
                        ? {
                            background: `linear-gradient(90deg, ${getColorVar(props.teamColor(column.mark), 600)}, ${getColorVar(props.teamColor(column.mark), 500)})`,
                          }
                        : undefined
                    }
                    onClick={() => props.onSelect(column.value)}
                  >
                    <Show when={column.mark === "x"}>
                      <IconX class="text-base" />
                    </Show>
                    <Show when={column.mark === "o"}>
                      <IconCircle class="text-sm" />
                    </Show>
                    <span class="truncate">{assignmentLabel(column.value)}</span>
                  </button>
                );
              }}
            </For>
          </div>
          <button class="cursor-pointer" type="button" onClick={() => props.onCycle("right")}>
            <IconTriangleRight />
          </button>
        </div>
      </div>
    </div>
  );
}
