/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoAuthImport } from './routes/_no-auth'
import { Route as AuthImport } from './routes/_auth'
import { Route as NoAuthVerifyEmailImport } from './routes/_no-auth/verify-email'
import { Route as NoAuthSignUpImport } from './routes/_no-auth/sign-up'
import { Route as NoAuthSignInImport } from './routes/_no-auth/sign-in'
import { Route as AuthEditProfileImport } from './routes/_auth/edit-profile'
import { Route as AuthCompleteProfileImport } from './routes/_auth/complete-profile'
import { Route as AuthNoLobbyImport } from './routes/_auth/_no-lobby'
import { Route as AuthLobbyImport } from './routes/_auth/_lobby'
import { Route as AuthLobbyIndexImport } from './routes/_auth/_lobby/index'
import { Route as AuthNoLobbyJoinImport } from './routes/_auth/_no-lobby/join'

// Create/Update Routes

const NoAuthRoute = NoAuthImport.update({
  id: '/_no-auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const NoAuthVerifyEmailRoute = NoAuthVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => NoAuthRoute,
} as any)

const NoAuthSignUpRoute = NoAuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => NoAuthRoute,
} as any)

const NoAuthSignInRoute = NoAuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => NoAuthRoute,
} as any)

const AuthEditProfileRoute = AuthEditProfileImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCompleteProfileRoute = AuthCompleteProfileImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthNoLobbyRoute = AuthNoLobbyImport.update({
  id: '/_no-lobby',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLobbyRoute = AuthLobbyImport.update({
  id: '/_lobby',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLobbyIndexRoute = AuthLobbyIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLobbyRoute,
} as any)

const AuthNoLobbyJoinRoute = AuthNoLobbyJoinImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthNoLobbyRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_no-auth': {
      id: '/_no-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoAuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_lobby': {
      id: '/_auth/_lobby'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLobbyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_no-lobby': {
      id: '/_auth/_no-lobby'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthNoLobbyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/complete-profile': {
      id: '/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/edit-profile': {
      id: '/_auth/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthEditProfileImport
      parentRoute: typeof AuthImport
    }
    '/_no-auth/sign-in': {
      id: '/_no-auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof NoAuthSignInImport
      parentRoute: typeof NoAuthImport
    }
    '/_no-auth/sign-up': {
      id: '/_no-auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof NoAuthSignUpImport
      parentRoute: typeof NoAuthImport
    }
    '/_no-auth/verify-email': {
      id: '/_no-auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof NoAuthVerifyEmailImport
      parentRoute: typeof NoAuthImport
    }
    '/_auth/_no-lobby/join': {
      id: '/_auth/_no-lobby/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthNoLobbyJoinImport
      parentRoute: typeof AuthNoLobbyImport
    }
    '/_auth/_lobby/': {
      id: '/_auth/_lobby/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLobbyIndexImport
      parentRoute: typeof AuthLobbyImport
    }
  }
}

// Create and export the route tree

interface AuthLobbyRouteChildren {
  AuthLobbyIndexRoute: typeof AuthLobbyIndexRoute
}

const AuthLobbyRouteChildren: AuthLobbyRouteChildren = {
  AuthLobbyIndexRoute: AuthLobbyIndexRoute,
}

const AuthLobbyRouteWithChildren = AuthLobbyRoute._addFileChildren(
  AuthLobbyRouteChildren,
)

interface AuthNoLobbyRouteChildren {
  AuthNoLobbyJoinRoute: typeof AuthNoLobbyJoinRoute
}

const AuthNoLobbyRouteChildren: AuthNoLobbyRouteChildren = {
  AuthNoLobbyJoinRoute: AuthNoLobbyJoinRoute,
}

const AuthNoLobbyRouteWithChildren = AuthNoLobbyRoute._addFileChildren(
  AuthNoLobbyRouteChildren,
)

interface AuthRouteChildren {
  AuthLobbyRoute: typeof AuthLobbyRouteWithChildren
  AuthNoLobbyRoute: typeof AuthNoLobbyRouteWithChildren
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthEditProfileRoute: typeof AuthEditProfileRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLobbyRoute: AuthLobbyRouteWithChildren,
  AuthNoLobbyRoute: AuthNoLobbyRouteWithChildren,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthEditProfileRoute: AuthEditProfileRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NoAuthRouteChildren {
  NoAuthSignInRoute: typeof NoAuthSignInRoute
  NoAuthSignUpRoute: typeof NoAuthSignUpRoute
  NoAuthVerifyEmailRoute: typeof NoAuthVerifyEmailRoute
}

const NoAuthRouteChildren: NoAuthRouteChildren = {
  NoAuthSignInRoute: NoAuthSignInRoute,
  NoAuthSignUpRoute: NoAuthSignUpRoute,
  NoAuthVerifyEmailRoute: NoAuthVerifyEmailRoute,
}

const NoAuthRouteWithChildren =
  NoAuthRoute._addFileChildren(NoAuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthNoLobbyRouteWithChildren
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/edit-profile': typeof AuthEditProfileRoute
  '/sign-in': typeof NoAuthSignInRoute
  '/sign-up': typeof NoAuthSignUpRoute
  '/verify-email': typeof NoAuthVerifyEmailRoute
  '/join': typeof AuthNoLobbyJoinRoute
  '/': typeof AuthLobbyIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthNoLobbyRouteWithChildren
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/edit-profile': typeof AuthEditProfileRoute
  '/sign-in': typeof NoAuthSignInRoute
  '/sign-up': typeof NoAuthSignUpRoute
  '/verify-email': typeof NoAuthVerifyEmailRoute
  '/join': typeof AuthNoLobbyJoinRoute
  '/': typeof AuthLobbyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_no-auth': typeof NoAuthRouteWithChildren
  '/_auth/_lobby': typeof AuthLobbyRouteWithChildren
  '/_auth/_no-lobby': typeof AuthNoLobbyRouteWithChildren
  '/_auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_auth/edit-profile': typeof AuthEditProfileRoute
  '/_no-auth/sign-in': typeof NoAuthSignInRoute
  '/_no-auth/sign-up': typeof NoAuthSignUpRoute
  '/_no-auth/verify-email': typeof NoAuthVerifyEmailRoute
  '/_auth/_no-lobby/join': typeof AuthNoLobbyJoinRoute
  '/_auth/_lobby/': typeof AuthLobbyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/complete-profile'
    | '/edit-profile'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/join'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/complete-profile'
    | '/edit-profile'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/join'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_no-auth'
    | '/_auth/_lobby'
    | '/_auth/_no-lobby'
    | '/_auth/complete-profile'
    | '/_auth/edit-profile'
    | '/_no-auth/sign-in'
    | '/_no-auth/sign-up'
    | '/_no-auth/verify-email'
    | '/_auth/_no-lobby/join'
    | '/_auth/_lobby/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  NoAuthRoute: typeof NoAuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  NoAuthRoute: NoAuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_no-auth"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_lobby",
        "/_auth/_no-lobby",
        "/_auth/complete-profile",
        "/_auth/edit-profile"
      ]
    },
    "/_no-auth": {
      "filePath": "_no-auth.tsx",
      "children": [
        "/_no-auth/sign-in",
        "/_no-auth/sign-up",
        "/_no-auth/verify-email"
      ]
    },
    "/_auth/_lobby": {
      "filePath": "_auth/_lobby.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_lobby/"
      ]
    },
    "/_auth/_no-lobby": {
      "filePath": "_auth/_no-lobby.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_no-lobby/join"
      ]
    },
    "/_auth/complete-profile": {
      "filePath": "_auth/complete-profile.tsx",
      "parent": "/_auth"
    },
    "/_auth/edit-profile": {
      "filePath": "_auth/edit-profile.tsx",
      "parent": "/_auth"
    },
    "/_no-auth/sign-in": {
      "filePath": "_no-auth/sign-in.tsx",
      "parent": "/_no-auth"
    },
    "/_no-auth/sign-up": {
      "filePath": "_no-auth/sign-up.tsx",
      "parent": "/_no-auth"
    },
    "/_no-auth/verify-email": {
      "filePath": "_no-auth/verify-email.tsx",
      "parent": "/_no-auth"
    },
    "/_auth/_no-lobby/join": {
      "filePath": "_auth/_no-lobby/join.tsx",
      "parent": "/_auth/_no-lobby"
    },
    "/_auth/_lobby/": {
      "filePath": "_auth/_lobby/index.tsx",
      "parent": "/_auth/_lobby"
    }
  }
}
ROUTE_MANIFEST_END */
