/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAuthRouteImport } from './routes/_no-auth'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as NoAuthVerifyEmailRouteImport } from './routes/_no-auth/verify-email'
import { Route as NoAuthSignUpRouteImport } from './routes/_no-auth/sign-up'
import { Route as NoAuthSignInRouteImport } from './routes/_no-auth/sign-in'
import { Route as NoAuthResetPasswordRouteImport } from './routes/_no-auth/reset-password'
import { Route as NoAuthForgotPasswordRouteImport } from './routes/_no-auth/forgot-password'
import { Route as AuthEditProfileRouteImport } from './routes/_auth/edit-profile'
import { Route as AuthCompleteProfileRouteImport } from './routes/_auth/complete-profile'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth/change-password'
import { Route as AuthNoLobbyRouteImport } from './routes/_auth/_no-lobby'
import { Route as AuthLobbyRouteImport } from './routes/_auth/_lobby'
import { Route as AuthClubsIndexRouteImport } from './routes/_auth/clubs/index'
import { Route as AuthLobbyIndexRouteImport } from './routes/_auth/_lobby/index'
import { Route as AuthClubsIdRouteImport } from './routes/_auth/clubs/$id'
import { Route as AuthNoLobbyJoinIndexRouteImport } from './routes/_auth/_no-lobby/join/index'
import { Route as AuthNoLobbyJoinIdRouteImport } from './routes/_auth/_no-lobby/join/$id'

const NoAuthRoute = NoAuthRouteImport.update({
  id: '/_no-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAuthVerifyEmailRoute = NoAuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthSignUpRoute = NoAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthSignInRoute = NoAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthResetPasswordRoute = NoAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => NoAuthRoute,
} as any)
const NoAuthForgotPasswordRoute = NoAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => NoAuthRoute,
} as any)
const AuthEditProfileRoute = AuthEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNoLobbyRoute = AuthNoLobbyRouteImport.update({
  id: '/_no-lobby',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLobbyRoute = AuthLobbyRouteImport.update({
  id: '/_lobby',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClubsIndexRoute = AuthClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLobbyIndexRoute = AuthLobbyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLobbyRoute,
} as any)
const AuthClubsIdRoute = AuthClubsIdRouteImport.update({
  id: '/clubs/$id',
  path: '/clubs/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNoLobbyJoinIndexRoute = AuthNoLobbyJoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => AuthNoLobbyRoute,
} as any)
const AuthNoLobbyJoinIdRoute = AuthNoLobbyJoinIdRouteImport.update({
  id: '/join/$id',
  path: '/join/$id',
  getParentRoute: () => AuthNoLobbyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/change-password': typeof AuthChangePasswordRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/edit-profile': typeof AuthEditProfileRoute
  '/forgot-password': typeof NoAuthForgotPasswordRoute
  '/reset-password': typeof NoAuthResetPasswordRoute
  '/sign-in': typeof NoAuthSignInRoute
  '/sign-up': typeof NoAuthSignUpRoute
  '/verify-email': typeof NoAuthVerifyEmailRoute
  '/clubs/$id': typeof AuthClubsIdRoute
  '/': typeof AuthLobbyIndexRoute
  '/clubs': typeof AuthClubsIndexRoute
  '/join/$id': typeof AuthNoLobbyJoinIdRoute
  '/join': typeof AuthNoLobbyJoinIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof AuthChangePasswordRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/edit-profile': typeof AuthEditProfileRoute
  '/forgot-password': typeof NoAuthForgotPasswordRoute
  '/reset-password': typeof NoAuthResetPasswordRoute
  '/sign-in': typeof NoAuthSignInRoute
  '/sign-up': typeof NoAuthSignUpRoute
  '/verify-email': typeof NoAuthVerifyEmailRoute
  '/clubs/$id': typeof AuthClubsIdRoute
  '/': typeof AuthLobbyIndexRoute
  '/clubs': typeof AuthClubsIndexRoute
  '/join/$id': typeof AuthNoLobbyJoinIdRoute
  '/join': typeof AuthNoLobbyJoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_no-auth': typeof NoAuthRouteWithChildren
  '/_auth/_lobby': typeof AuthLobbyRouteWithChildren
  '/_auth/_no-lobby': typeof AuthNoLobbyRouteWithChildren
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_auth/edit-profile': typeof AuthEditProfileRoute
  '/_no-auth/forgot-password': typeof NoAuthForgotPasswordRoute
  '/_no-auth/reset-password': typeof NoAuthResetPasswordRoute
  '/_no-auth/sign-in': typeof NoAuthSignInRoute
  '/_no-auth/sign-up': typeof NoAuthSignUpRoute
  '/_no-auth/verify-email': typeof NoAuthVerifyEmailRoute
  '/_auth/clubs/$id': typeof AuthClubsIdRoute
  '/_auth/_lobby/': typeof AuthLobbyIndexRoute
  '/_auth/clubs/': typeof AuthClubsIndexRoute
  '/_auth/_no-lobby/join/$id': typeof AuthNoLobbyJoinIdRoute
  '/_auth/_no-lobby/join/': typeof AuthNoLobbyJoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/change-password'
    | '/complete-profile'
    | '/edit-profile'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/clubs/$id'
    | '/'
    | '/clubs'
    | '/join/$id'
    | '/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/complete-profile'
    | '/edit-profile'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/clubs/$id'
    | '/'
    | '/clubs'
    | '/join/$id'
    | '/join'
  id:
    | '__root__'
    | '/_auth'
    | '/_no-auth'
    | '/_auth/_lobby'
    | '/_auth/_no-lobby'
    | '/_auth/change-password'
    | '/_auth/complete-profile'
    | '/_auth/edit-profile'
    | '/_no-auth/forgot-password'
    | '/_no-auth/reset-password'
    | '/_no-auth/sign-in'
    | '/_no-auth/sign-up'
    | '/_no-auth/verify-email'
    | '/_auth/clubs/$id'
    | '/_auth/_lobby/'
    | '/_auth/clubs/'
    | '/_auth/_no-lobby/join/$id'
    | '/_auth/_no-lobby/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  NoAuthRoute: typeof NoAuthRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_no-auth': {
      id: '/_no-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_no-auth/verify-email': {
      id: '/_no-auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof NoAuthVerifyEmailRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/sign-up': {
      id: '/_no-auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof NoAuthSignUpRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/sign-in': {
      id: '/_no-auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof NoAuthSignInRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/reset-password': {
      id: '/_no-auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof NoAuthResetPasswordRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_no-auth/forgot-password': {
      id: '/_no-auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof NoAuthForgotPasswordRouteImport
      parentRoute: typeof NoAuthRoute
    }
    '/_auth/edit-profile': {
      id: '/_auth/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthEditProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/complete-profile': {
      id: '/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_no-lobby': {
      id: '/_auth/_no-lobby'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthNoLobbyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_lobby': {
      id: '/_auth/_lobby'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLobbyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clubs/': {
      id: '/_auth/clubs/'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AuthClubsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_lobby/': {
      id: '/_auth/_lobby/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLobbyIndexRouteImport
      parentRoute: typeof AuthLobbyRoute
    }
    '/_auth/clubs/$id': {
      id: '/_auth/clubs/$id'
      path: '/clubs/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof AuthClubsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_no-lobby/join/': {
      id: '/_auth/_no-lobby/join/'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthNoLobbyJoinIndexRouteImport
      parentRoute: typeof AuthNoLobbyRoute
    }
    '/_auth/_no-lobby/join/$id': {
      id: '/_auth/_no-lobby/join/$id'
      path: '/join/$id'
      fullPath: '/join/$id'
      preLoaderRoute: typeof AuthNoLobbyJoinIdRouteImport
      parentRoute: typeof AuthNoLobbyRoute
    }
  }
}

interface AuthLobbyRouteChildren {
  AuthLobbyIndexRoute: typeof AuthLobbyIndexRoute
}

const AuthLobbyRouteChildren: AuthLobbyRouteChildren = {
  AuthLobbyIndexRoute: AuthLobbyIndexRoute,
}

const AuthLobbyRouteWithChildren = AuthLobbyRoute._addFileChildren(
  AuthLobbyRouteChildren,
)

interface AuthNoLobbyRouteChildren {
  AuthNoLobbyJoinIdRoute: typeof AuthNoLobbyJoinIdRoute
  AuthNoLobbyJoinIndexRoute: typeof AuthNoLobbyJoinIndexRoute
}

const AuthNoLobbyRouteChildren: AuthNoLobbyRouteChildren = {
  AuthNoLobbyJoinIdRoute: AuthNoLobbyJoinIdRoute,
  AuthNoLobbyJoinIndexRoute: AuthNoLobbyJoinIndexRoute,
}

const AuthNoLobbyRouteWithChildren = AuthNoLobbyRoute._addFileChildren(
  AuthNoLobbyRouteChildren,
)

interface AuthRouteChildren {
  AuthLobbyRoute: typeof AuthLobbyRouteWithChildren
  AuthNoLobbyRoute: typeof AuthNoLobbyRouteWithChildren
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthEditProfileRoute: typeof AuthEditProfileRoute
  AuthClubsIdRoute: typeof AuthClubsIdRoute
  AuthClubsIndexRoute: typeof AuthClubsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLobbyRoute: AuthLobbyRouteWithChildren,
  AuthNoLobbyRoute: AuthNoLobbyRouteWithChildren,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthEditProfileRoute: AuthEditProfileRoute,
  AuthClubsIdRoute: AuthClubsIdRoute,
  AuthClubsIndexRoute: AuthClubsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NoAuthRouteChildren {
  NoAuthForgotPasswordRoute: typeof NoAuthForgotPasswordRoute
  NoAuthResetPasswordRoute: typeof NoAuthResetPasswordRoute
  NoAuthSignInRoute: typeof NoAuthSignInRoute
  NoAuthSignUpRoute: typeof NoAuthSignUpRoute
  NoAuthVerifyEmailRoute: typeof NoAuthVerifyEmailRoute
}

const NoAuthRouteChildren: NoAuthRouteChildren = {
  NoAuthForgotPasswordRoute: NoAuthForgotPasswordRoute,
  NoAuthResetPasswordRoute: NoAuthResetPasswordRoute,
  NoAuthSignInRoute: NoAuthSignInRoute,
  NoAuthSignUpRoute: NoAuthSignUpRoute,
  NoAuthVerifyEmailRoute: NoAuthVerifyEmailRoute,
}

const NoAuthRouteWithChildren =
  NoAuthRoute._addFileChildren(NoAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  NoAuthRoute: NoAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
