/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsOfServiceImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyImport } from './routes/privacy-policy'
import { Route as IndexImport } from './routes/index'
import { Route as DownloadWindowsImport } from './routes/download/windows'
import { Route as DownloadMacosImport } from './routes/download/macos'
import { Route as DownloadLinuxImport } from './routes/download/linux'

// Create/Update Routes

const TermsOfServiceRoute = TermsOfServiceImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyPolicyRoute = PrivacyPolicyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DownloadWindowsRoute = DownloadWindowsImport.update({
  id: '/download/windows',
  path: '/download/windows',
  getParentRoute: () => rootRoute,
} as any)

const DownloadMacosRoute = DownloadMacosImport.update({
  id: '/download/macos',
  path: '/download/macos',
  getParentRoute: () => rootRoute,
} as any)

const DownloadLinuxRoute = DownloadLinuxImport.update({
  id: '/download/linux',
  path: '/download/linux',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceImport
      parentRoute: typeof rootRoute
    }
    '/download/linux': {
      id: '/download/linux'
      path: '/download/linux'
      fullPath: '/download/linux'
      preLoaderRoute: typeof DownloadLinuxImport
      parentRoute: typeof rootRoute
    }
    '/download/macos': {
      id: '/download/macos'
      path: '/download/macos'
      fullPath: '/download/macos'
      preLoaderRoute: typeof DownloadMacosImport
      parentRoute: typeof rootRoute
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/download/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/macos': typeof DownloadMacosRoute
  '/download/windows': typeof DownloadWindowsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/download/linux'
    | '/download/macos'
    | '/download/windows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/download/linux'
    | '/download/macos'
    | '/download/windows'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/download/linux'
    | '/download/macos'
    | '/download/windows'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  DownloadLinuxRoute: typeof DownloadLinuxRoute
  DownloadMacosRoute: typeof DownloadMacosRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  DownloadLinuxRoute: DownloadLinuxRoute,
  DownloadMacosRoute: DownloadMacosRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/privacy-policy",
        "/terms-of-service",
        "/download/linux",
        "/download/macos",
        "/download/windows"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.tsx"
    },
    "/terms-of-service": {
      "filePath": "terms-of-service.tsx"
    },
    "/download/linux": {
      "filePath": "download/linux.tsx"
    },
    "/download/macos": {
      "filePath": "download/macos.tsx"
    },
    "/download/windows": {
      "filePath": "download/windows.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
