// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getMicrophones: () => typedError<Microphone[], AppError>(__TAURI_INVOKE("get_microphones")),
	startRecording: (options: MicrophoneOptions[], playbackEnabled: boolean, playbackVolume: number | null) => typedError<null, AppError>(__TAURI_INVOKE("start_recording", { options, playbackEnabled, playbackVolume })),
	stopRecording: () => typedError<null, AppError>(__TAURI_INVOKE("stop_recording")),
	getPitches: (windowMs: number | null) => typedError<(number | null)[], AppError>(__TAURI_INVOKE("get_pitches", { windowMs })),
	getAudioLevels: () => typedError<(number | null)[], AppError>(__TAURI_INVOKE("get_audio_levels")),
	getMediaServerBaseUrl: () => typedError<string | null, string>(__TAURI_INVOKE("get_media_server_base_url")),
	parseSongsFromPaths: (paths: string[]) => typedError<SongGroup[], AppError>(__TAURI_INVOKE("parse_songs_from_paths", { paths })),
	webrtcCreateAnswer: (userId: string, offerSdp: string, iceServers: IceServerConfig_Deserialize[]) => typedError<string, AppError>(__TAURI_INVOKE("webrtc_create_answer", { userId, offerSdp, iceServers })),
	webrtcAddIceCandidate: (userId: string, candidate: string) => typedError<null, AppError>(__TAURI_INVOKE("webrtc_add_ice_candidate", { userId, candidate })),
	webrtcSendMessage: (userId: string, label: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("webrtc_send_message", { userId, label, data })),
	webrtcCloseConnection: (userId: string) => typedError<null, AppError>(__TAURI_INVOKE("webrtc_close_connection", { userId })),
	webrtcCloseAll: () => typedError<null, AppError>(__TAURI_INVOKE("webrtc_close_all")),
	usdbLogin: (username: string, password: string) => typedError<boolean, AppError>(__TAURI_INVOKE("usdb_login", { username, password })),
	usdbLogout: () => typedError<null, AppError>(__TAURI_INVOKE("usdb_logout")),
	usdbIsLoggedIn: () => typedError<boolean, AppError>(__TAURI_INVOKE("usdb_is_logged_in")),
	/**  Full fetch if `last_mtime == 0`, otherwise incremental sync from the watermark. */
	usdbFetchCatalog: (lastMtime: number, lastSongIds: number[]) => typedError<UsdbSearchEntry[], AppError>(__TAURI_INVOKE("usdb_fetch_catalog", { lastMtime, lastSongIds })),
	usdbGetSongPreview: (songId: number) => typedError<UsdbSongPreview, AppError>(__TAURI_INVOKE("usdb_get_song_preview", { songId })),
	usdbGetSong: (songId: number) => typedError<UsdbSong, AppError>(__TAURI_INVOKE("usdb_get_song", { songId })),
};

/** Events */
export const events = {
	channelCloseEvent: makeEvent<ChannelCloseEvent>("channel-close-event"),
	channelMessageEvent: makeEvent<ChannelMessageEvent>("channel-message-event"),
	channelOpenEvent: makeEvent<ChannelOpenEvent>("channel-open-event"),
	connectionStateEvent: makeEvent<ConnectionStateEvent>("connection-state-event"),
	iceCandidateEvent: makeEvent<IceCandidateEvent>("ice-candidate-event"),
	progressEvent: makeEvent<ProgressEvent>("progress-event"),
	startParsingEvent: makeEvent<StartParsingEvent>("start-parsing-event"),
	usdbSyncProgressEvent: makeEvent<UsdbSyncProgressEvent>("usdb-sync-progress-event"),
};

/* Types */
export type AppError = { type: "IoError"; data: string } | { type: "LoftyError"; data: string } | { type: "RecorderError"; data: string } | { type: "ProcessorError"; data: string } | { type: "CpalError"; data: string } | { type: "UltrastarError"; data: string } | { type: "WebRTCError"; data: string } | { type: "UsdbError"; data: string };

export type ChannelCloseEvent = {
	userId: string,
	label: string,
};

export type ChannelMessageEvent = {
	userId: string,
	label: string,
	data: string,
};

export type ChannelOpenEvent = {
	userId: string,
	label: string,
};

export type ConnectionStateEvent = {
	userId: string,
	state: string,
};

export type IceCandidateEvent = {
	userId: string,
	candidate: string,
};

export type IceServerConfig = IceServerConfig_Serialize | IceServerConfig_Deserialize;

export type IceServerConfig_Deserialize = {
	urls: IceServerUrls,
	username: string | null,
	credential: string | null,
};

export type IceServerConfig_Serialize = {
	urls: IceServerUrls,
	username?: string | null,
	credential?: string | null,
};

export type IceServerUrls = string | string[];

export type LocalSong = {
	audioUrl: string | null,
	instrumentalUrl: string | null,
	videoUrl: string | null,
	coverUrl: string | null,
	backgroundUrl: string | null,
	replayGainTrackGain: number | null,
	replayGainTrackPeak: number | null,
} & Song;

export type Microphone = {
	name: string,
	channels: number,
};

/**  Configuration options for a microphone input */
export type MicrophoneOptions = {
	name: string,
	channel: number,
	gain: number | null,
	threshold: number | null,
	/**
	 *  Input latency in ms. The pitch window ends this far in the past so the
	 *  detected pitch matches the audio sung for the current beat.
	 */
	delay: number | null,
};

export type Note = {
	type: NoteType,
	startBeat: number,
	length: number,
	text: string,
	txtPitch: number,
	midiNote: number,
};

export type NoteType = "Normal" | "Golden" | "Freestyle" | "Rap" | "RapGolden";

export type Phrase = {
	disappearBeat: number,
	notes: Note[],
};

export type ProgressEvent = {
	song: string,
};

export type Song = {
	title: string,
	artist: string,
	bpm: number | null,
	gap: number | null,
	videoGap: number | null,
	start: number | null,
	end: number | null,
	hash: string,
	album: string | null,
	language: string[] | null,
	edition: string[] | null,
	genre: string[] | null,
	year: number | null,
	creator: string[] | null,
	relative: boolean | null,
	audio: string | null,
	instrumental: string | null,
	cover: string | null,
	video: string | null,
	background: string | null,
	p1: string | null,
	p2: string | null,
	previewStart: number | null,
	version: string | null,
	tags: string[] | null,
	medleyStartBeat: number | null,
	medleyEndBeat: number | null,
	medleyStart: number | null,
	medleyEnd: number | null,
	voices: Voice[],
};

export type SongGroup = {
	path: string,
	songs: LocalSong[],
};

export type StartParsingEvent = {
	total_songs: number,
};

/**  Lightweight entry from USDB search results (no note data). */
export type UsdbSearchEntry = {
	songId: number,
	artist: string,
	title: string,
	genre: string,
	year: number | null,
	language: string,
	creator: string,
	edition: string,
	goldenNotes: boolean,
	rating: number | null,
	views: number,
	coverUrl: string | null,
	sampleUrl: string | null,
	/**  Unix timestamp from USDB's `data-lastchange` attribute. */
	usdbMtime: number,
};

/**  Full USDB song with parsed note data, ready for gameplay. */
export type UsdbSong = {
	songId: number,
	/**  YouTube ID for audio playback (from `a=` tag). Notes/GAP are timed to this. */
	audioYoutubeId: string | null,
	/**  YouTube ID for video (from `v=` tag). Shown as visual, muted if separate audio exists. */
	videoYoutubeId: string | null,
	coverUrl: string | null,
} & Song;

/**  Preview info for the search UI (YouTube ID, BPM, etc. — no note data). */
export type UsdbSongPreview = {
	song: UsdbSearchEntry,
	youtubeId: string | null,
	videoUrl: string | null,
	bpm: number | null,
	gap: number | null,
};

/**  Emitted after each catalog page is fetched so the UI can show sync progress. */
export type UsdbSyncProgressEvent = {
	fetched: number,
	total: number,
};

export type Voice = {
	phrases: Phrase[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

