/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuitRouteImport } from './routes/quit'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CreateLobbyRouteImport } from './routes/create-lobby'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SingIndexRouteImport } from './routes/sing/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PartyIndexRouteImport } from './routes/party/index'
import { Route as LobbyIndexRouteImport } from './routes/lobby/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as SingSelectRouteImport } from './routes/sing/select'
import { Route as SingMedleyRouteImport } from './routes/sing/medley'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as LobbySelectClubRouteImport } from './routes/lobby/select-club'
import { Route as LobbyAddLocalPlayerRouteImport } from './routes/lobby/add-local-player'
import { Route as LobbyIdRouteImport } from './routes/lobby/$id'
import { Route as GameScoreRouteImport } from './routes/game/score'
import { Route as GameRestartRouteImport } from './routes/game/restart'
import { Route as GameNextRouteImport } from './routes/game/next'
import { Route as SettingsVolumeIndexRouteImport } from './routes/settings/volume/index'
import { Route as SettingsSongsIndexRouteImport } from './routes/settings/songs/index'
import { Route as SettingsMicrophonesIndexRouteImport } from './routes/settings/microphones/index'
import { Route as SettingsLocalPlayersIndexRouteImport } from './routes/settings/local-players/index'
import { Route as SettingsGeneralIndexRouteImport } from './routes/settings/general/index'
import { Route as PartyVersusIndexRouteImport } from './routes/party/versus/index'
import { Route as SettingsSongsPathRouteImport } from './routes/settings/songs/$path'
import { Route as SettingsMicrophonesIdRouteImport } from './routes/settings/microphones/$id'
import { Route as SettingsLocalPlayersIdRouteImport } from './routes/settings/local-players/$id'
import { Route as PartyVersusSettingsRouteImport } from './routes/party/versus/settings'
import { Route as LobbyLocalIdRouteImport } from './routes/lobby/local/$id'

const QuitRoute = QuitRouteImport.update({
  id: '/quit',
  path: '/quit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateLobbyRoute = CreateLobbyRouteImport.update({
  id: '/create-lobby',
  path: '/create-lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SingIndexRoute = SingIndexRouteImport.update({
  id: '/sing/',
  path: '/sing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyIndexRoute = PartyIndexRouteImport.update({
  id: '/party/',
  path: '/party/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyIndexRoute = LobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const SingSelectRoute = SingSelectRouteImport.update({
  id: '/sing/select',
  path: '/sing/select',
  getParentRoute: () => rootRouteImport,
} as any)
const SingMedleyRoute = SingMedleyRouteImport.update({
  id: '/sing/medley',
  path: '/sing/medley',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbySelectClubRoute = LobbySelectClubRouteImport.update({
  id: '/lobby/select-club',
  path: '/lobby/select-club',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyAddLocalPlayerRoute = LobbyAddLocalPlayerRouteImport.update({
  id: '/lobby/add-local-player',
  path: '/lobby/add-local-player',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyIdRoute = LobbyIdRouteImport.update({
  id: '/lobby/$id',
  path: '/lobby/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameScoreRoute = GameScoreRouteImport.update({
  id: '/game/score',
  path: '/game/score',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRestartRoute = GameRestartRouteImport.update({
  id: '/game/restart',
  path: '/game/restart',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNextRoute = GameNextRouteImport.update({
  id: '/game/next',
  path: '/game/next',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVolumeIndexRoute = SettingsVolumeIndexRouteImport.update({
  id: '/settings/volume/',
  path: '/settings/volume/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSongsIndexRoute = SettingsSongsIndexRouteImport.update({
  id: '/settings/songs/',
  path: '/settings/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMicrophonesIndexRoute =
  SettingsMicrophonesIndexRouteImport.update({
    id: '/settings/microphones/',
    path: '/settings/microphones/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsLocalPlayersIndexRoute =
  SettingsLocalPlayersIndexRouteImport.update({
    id: '/settings/local-players/',
    path: '/settings/local-players/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsGeneralIndexRoute = SettingsGeneralIndexRouteImport.update({
  id: '/settings/general/',
  path: '/settings/general/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyVersusIndexRoute = PartyVersusIndexRouteImport.update({
  id: '/party/versus/',
  path: '/party/versus/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSongsPathRoute = SettingsSongsPathRouteImport.update({
  id: '/settings/songs/$path',
  path: '/settings/songs/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMicrophonesIdRoute = SettingsMicrophonesIdRouteImport.update({
  id: '/settings/microphones/$id',
  path: '/settings/microphones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLocalPlayersIdRoute = SettingsLocalPlayersIdRouteImport.update({
  id: '/settings/local-players/$id',
  path: '/settings/local-players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyVersusSettingsRoute = PartyVersusSettingsRouteImport.update({
  id: '/party/versus/settings',
  path: '/party/versus/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLocalIdRoute = LobbyLocalIdRouteImport.update({
  id: '/lobby/local/$id',
  path: '/lobby/local/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-lobby': typeof CreateLobbyRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/quit': typeof QuitRoute
  '/game/next': typeof GameNextRoute
  '/game/restart': typeof GameRestartRoute
  '/game/score': typeof GameScoreRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/lobby/add-local-player': typeof LobbyAddLocalPlayerRoute
  '/lobby/select-club': typeof LobbySelectClubRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/sing/medley': typeof SingMedleyRoute
  '/sing/select': typeof SingSelectRoute
  '/game': typeof GameIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/party': typeof PartyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sing': typeof SingIndexRoute
  '/lobby/local/$id': typeof LobbyLocalIdRoute
  '/party/versus/settings': typeof PartyVersusSettingsRoute
  '/settings/local-players/$id': typeof SettingsLocalPlayersIdRoute
  '/settings/microphones/$id': typeof SettingsMicrophonesIdRoute
  '/settings/songs/$path': typeof SettingsSongsPathRoute
  '/party/versus': typeof PartyVersusIndexRoute
  '/settings/general': typeof SettingsGeneralIndexRoute
  '/settings/local-players': typeof SettingsLocalPlayersIndexRoute
  '/settings/microphones': typeof SettingsMicrophonesIndexRoute
  '/settings/songs': typeof SettingsSongsIndexRoute
  '/settings/volume': typeof SettingsVolumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-lobby': typeof CreateLobbyRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/quit': typeof QuitRoute
  '/game/next': typeof GameNextRoute
  '/game/restart': typeof GameRestartRoute
  '/game/score': typeof GameScoreRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/lobby/add-local-player': typeof LobbyAddLocalPlayerRoute
  '/lobby/select-club': typeof LobbySelectClubRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/sing/medley': typeof SingMedleyRoute
  '/sing/select': typeof SingSelectRoute
  '/game': typeof GameIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/party': typeof PartyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sing': typeof SingIndexRoute
  '/lobby/local/$id': typeof LobbyLocalIdRoute
  '/party/versus/settings': typeof PartyVersusSettingsRoute
  '/settings/local-players/$id': typeof SettingsLocalPlayersIdRoute
  '/settings/microphones/$id': typeof SettingsMicrophonesIdRoute
  '/settings/songs/$path': typeof SettingsSongsPathRoute
  '/party/versus': typeof PartyVersusIndexRoute
  '/settings/general': typeof SettingsGeneralIndexRoute
  '/settings/local-players': typeof SettingsLocalPlayersIndexRoute
  '/settings/microphones': typeof SettingsMicrophonesIndexRoute
  '/settings/songs': typeof SettingsSongsIndexRoute
  '/settings/volume': typeof SettingsVolumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-lobby': typeof CreateLobbyRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/quit': typeof QuitRoute
  '/game/next': typeof GameNextRoute
  '/game/restart': typeof GameRestartRoute
  '/game/score': typeof GameScoreRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/lobby/add-local-player': typeof LobbyAddLocalPlayerRoute
  '/lobby/select-club': typeof LobbySelectClubRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/sing/medley': typeof SingMedleyRoute
  '/sing/select': typeof SingSelectRoute
  '/game/': typeof GameIndexRoute
  '/lobby/': typeof LobbyIndexRoute
  '/party/': typeof PartyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sing/': typeof SingIndexRoute
  '/lobby/local/$id': typeof LobbyLocalIdRoute
  '/party/versus/settings': typeof PartyVersusSettingsRoute
  '/settings/local-players/$id': typeof SettingsLocalPlayersIdRoute
  '/settings/microphones/$id': typeof SettingsMicrophonesIdRoute
  '/settings/songs/$path': typeof SettingsSongsPathRoute
  '/party/versus/': typeof PartyVersusIndexRoute
  '/settings/general/': typeof SettingsGeneralIndexRoute
  '/settings/local-players/': typeof SettingsLocalPlayersIndexRoute
  '/settings/microphones/': typeof SettingsMicrophonesIndexRoute
  '/settings/songs/': typeof SettingsSongsIndexRoute
  '/settings/volume/': typeof SettingsVolumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-lobby'
    | '/home'
    | '/loading'
    | '/quit'
    | '/game/next'
    | '/game/restart'
    | '/game/score'
    | '/lobby/$id'
    | '/lobby/add-local-player'
    | '/lobby/select-club'
    | '/settings/credits'
    | '/sing/medley'
    | '/sing/select'
    | '/game'
    | '/lobby'
    | '/party'
    | '/settings'
    | '/sing'
    | '/lobby/local/$id'
    | '/party/versus/settings'
    | '/settings/local-players/$id'
    | '/settings/microphones/$id'
    | '/settings/songs/$path'
    | '/party/versus'
    | '/settings/general'
    | '/settings/local-players'
    | '/settings/microphones'
    | '/settings/songs'
    | '/settings/volume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-lobby'
    | '/home'
    | '/loading'
    | '/quit'
    | '/game/next'
    | '/game/restart'
    | '/game/score'
    | '/lobby/$id'
    | '/lobby/add-local-player'
    | '/lobby/select-club'
    | '/settings/credits'
    | '/sing/medley'
    | '/sing/select'
    | '/game'
    | '/lobby'
    | '/party'
    | '/settings'
    | '/sing'
    | '/lobby/local/$id'
    | '/party/versus/settings'
    | '/settings/local-players/$id'
    | '/settings/microphones/$id'
    | '/settings/songs/$path'
    | '/party/versus'
    | '/settings/general'
    | '/settings/local-players'
    | '/settings/microphones'
    | '/settings/songs'
    | '/settings/volume'
  id:
    | '__root__'
    | '/'
    | '/create-lobby'
    | '/home'
    | '/loading'
    | '/quit'
    | '/game/next'
    | '/game/restart'
    | '/game/score'
    | '/lobby/$id'
    | '/lobby/add-local-player'
    | '/lobby/select-club'
    | '/settings/credits'
    | '/sing/medley'
    | '/sing/select'
    | '/game/'
    | '/lobby/'
    | '/party/'
    | '/settings/'
    | '/sing/'
    | '/lobby/local/$id'
    | '/party/versus/settings'
    | '/settings/local-players/$id'
    | '/settings/microphones/$id'
    | '/settings/songs/$path'
    | '/party/versus/'
    | '/settings/general/'
    | '/settings/local-players/'
    | '/settings/microphones/'
    | '/settings/songs/'
    | '/settings/volume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateLobbyRoute: typeof CreateLobbyRoute
  HomeRoute: typeof HomeRoute
  LoadingRoute: typeof LoadingRoute
  QuitRoute: typeof QuitRoute
  GameNextRoute: typeof GameNextRoute
  GameRestartRoute: typeof GameRestartRoute
  GameScoreRoute: typeof GameScoreRoute
  LobbyIdRoute: typeof LobbyIdRoute
  LobbyAddLocalPlayerRoute: typeof LobbyAddLocalPlayerRoute
  LobbySelectClubRoute: typeof LobbySelectClubRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SingMedleyRoute: typeof SingMedleyRoute
  SingSelectRoute: typeof SingSelectRoute
  GameIndexRoute: typeof GameIndexRoute
  LobbyIndexRoute: typeof LobbyIndexRoute
  PartyIndexRoute: typeof PartyIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SingIndexRoute: typeof SingIndexRoute
  LobbyLocalIdRoute: typeof LobbyLocalIdRoute
  PartyVersusSettingsRoute: typeof PartyVersusSettingsRoute
  SettingsLocalPlayersIdRoute: typeof SettingsLocalPlayersIdRoute
  SettingsMicrophonesIdRoute: typeof SettingsMicrophonesIdRoute
  SettingsSongsPathRoute: typeof SettingsSongsPathRoute
  PartyVersusIndexRoute: typeof PartyVersusIndexRoute
  SettingsGeneralIndexRoute: typeof SettingsGeneralIndexRoute
  SettingsLocalPlayersIndexRoute: typeof SettingsLocalPlayersIndexRoute
  SettingsMicrophonesIndexRoute: typeof SettingsMicrophonesIndexRoute
  SettingsSongsIndexRoute: typeof SettingsSongsIndexRoute
  SettingsVolumeIndexRoute: typeof SettingsVolumeIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/quit': {
      id: '/quit'
      path: '/quit'
      fullPath: '/quit'
      preLoaderRoute: typeof QuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-lobby': {
      id: '/create-lobby'
      path: '/create-lobby'
      fullPath: '/create-lobby'
      preLoaderRoute: typeof CreateLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sing/': {
      id: '/sing/'
      path: '/sing'
      fullPath: '/sing'
      preLoaderRoute: typeof SingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/': {
      id: '/party/'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/': {
      id: '/lobby/'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sing/select': {
      id: '/sing/select'
      path: '/sing/select'
      fullPath: '/sing/select'
      preLoaderRoute: typeof SingSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sing/medley': {
      id: '/sing/medley'
      path: '/sing/medley'
      fullPath: '/sing/medley'
      preLoaderRoute: typeof SingMedleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/settings/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/select-club': {
      id: '/lobby/select-club'
      path: '/lobby/select-club'
      fullPath: '/lobby/select-club'
      preLoaderRoute: typeof LobbySelectClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/add-local-player': {
      id: '/lobby/add-local-player'
      path: '/lobby/add-local-player'
      fullPath: '/lobby/add-local-player'
      preLoaderRoute: typeof LobbyAddLocalPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$id': {
      id: '/lobby/$id'
      path: '/lobby/$id'
      fullPath: '/lobby/$id'
      preLoaderRoute: typeof LobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/score': {
      id: '/game/score'
      path: '/game/score'
      fullPath: '/game/score'
      preLoaderRoute: typeof GameScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/restart': {
      id: '/game/restart'
      path: '/game/restart'
      fullPath: '/game/restart'
      preLoaderRoute: typeof GameRestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/next': {
      id: '/game/next'
      path: '/game/next'
      fullPath: '/game/next'
      preLoaderRoute: typeof GameNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/volume/': {
      id: '/settings/volume/'
      path: '/settings/volume'
      fullPath: '/settings/volume'
      preLoaderRoute: typeof SettingsVolumeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/songs/': {
      id: '/settings/songs/'
      path: '/settings/songs'
      fullPath: '/settings/songs'
      preLoaderRoute: typeof SettingsSongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/microphones/': {
      id: '/settings/microphones/'
      path: '/settings/microphones'
      fullPath: '/settings/microphones'
      preLoaderRoute: typeof SettingsMicrophonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/local-players/': {
      id: '/settings/local-players/'
      path: '/settings/local-players'
      fullPath: '/settings/local-players'
      preLoaderRoute: typeof SettingsLocalPlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general/': {
      id: '/settings/general/'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/versus/': {
      id: '/party/versus/'
      path: '/party/versus'
      fullPath: '/party/versus'
      preLoaderRoute: typeof PartyVersusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/songs/$path': {
      id: '/settings/songs/$path'
      path: '/settings/songs/$path'
      fullPath: '/settings/songs/$path'
      preLoaderRoute: typeof SettingsSongsPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/microphones/$id': {
      id: '/settings/microphones/$id'
      path: '/settings/microphones/$id'
      fullPath: '/settings/microphones/$id'
      preLoaderRoute: typeof SettingsMicrophonesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/local-players/$id': {
      id: '/settings/local-players/$id'
      path: '/settings/local-players/$id'
      fullPath: '/settings/local-players/$id'
      preLoaderRoute: typeof SettingsLocalPlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/versus/settings': {
      id: '/party/versus/settings'
      path: '/party/versus/settings'
      fullPath: '/party/versus/settings'
      preLoaderRoute: typeof PartyVersusSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/local/$id': {
      id: '/lobby/local/$id'
      path: '/lobby/local/$id'
      fullPath: '/lobby/local/$id'
      preLoaderRoute: typeof LobbyLocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateLobbyRoute: CreateLobbyRoute,
  HomeRoute: HomeRoute,
  LoadingRoute: LoadingRoute,
  QuitRoute: QuitRoute,
  GameNextRoute: GameNextRoute,
  GameRestartRoute: GameRestartRoute,
  GameScoreRoute: GameScoreRoute,
  LobbyIdRoute: LobbyIdRoute,
  LobbyAddLocalPlayerRoute: LobbyAddLocalPlayerRoute,
  LobbySelectClubRoute: LobbySelectClubRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SingMedleyRoute: SingMedleyRoute,
  SingSelectRoute: SingSelectRoute,
  GameIndexRoute: GameIndexRoute,
  LobbyIndexRoute: LobbyIndexRoute,
  PartyIndexRoute: PartyIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SingIndexRoute: SingIndexRoute,
  LobbyLocalIdRoute: LobbyLocalIdRoute,
  PartyVersusSettingsRoute: PartyVersusSettingsRoute,
  SettingsLocalPlayersIdRoute: SettingsLocalPlayersIdRoute,
  SettingsMicrophonesIdRoute: SettingsMicrophonesIdRoute,
  SettingsSongsPathRoute: SettingsSongsPathRoute,
  PartyVersusIndexRoute: PartyVersusIndexRoute,
  SettingsGeneralIndexRoute: SettingsGeneralIndexRoute,
  SettingsLocalPlayersIndexRoute: SettingsLocalPlayersIndexRoute,
  SettingsMicrophonesIndexRoute: SettingsMicrophonesIndexRoute,
  SettingsSongsIndexRoute: SettingsSongsIndexRoute,
  SettingsVolumeIndexRoute: SettingsVolumeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
