/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoadingImport } from './routes/loading'
import { Route as HomeImport } from './routes/home'
import { Route as CreateLobbyImport } from './routes/create-lobby'
import { Route as IndexImport } from './routes/index'
import { Route as SingIndexImport } from './routes/sing/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as PartyIndexImport } from './routes/party/index'
import { Route as LobbyIndexImport } from './routes/lobby/index'
import { Route as GameIndexImport } from './routes/game/index'
import { Route as SingHashImport } from './routes/sing/$hash'
import { Route as SettingsCreditsImport } from './routes/settings/credits'
import { Route as LobbyIdImport } from './routes/lobby/$id'
import { Route as GameScoreImport } from './routes/game/score'
import { Route as SettingsVolumeIndexImport } from './routes/settings/volume/index'
import { Route as SettingsSongsIndexImport } from './routes/settings/songs/index'
import { Route as SettingsMicrophonesIndexImport } from './routes/settings/microphones/index'
import { Route as SettingsGeneralIndexImport } from './routes/settings/general/index'
import { Route as PartyVersusIndexImport } from './routes/party/versus/index'
import { Route as SettingsSongsPathImport } from './routes/settings/songs/$path'
import { Route as SettingsMicrophonesIdImport } from './routes/settings/microphones/$id'
import { Route as PartyVersusSettingsImport } from './routes/party/versus/settings'

// Create/Update Routes

const LoadingRoute = LoadingImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const CreateLobbyRoute = CreateLobbyImport.update({
  id: '/create-lobby',
  path: '/create-lobby',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SingIndexRoute = SingIndexImport.update({
  id: '/sing/',
  path: '/sing/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const PartyIndexRoute = PartyIndexImport.update({
  id: '/party/',
  path: '/party/',
  getParentRoute: () => rootRoute,
} as any)

const LobbyIndexRoute = LobbyIndexImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => rootRoute,
} as any)

const GameIndexRoute = GameIndexImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRoute,
} as any)

const SingHashRoute = SingHashImport.update({
  id: '/sing/$hash',
  path: '/sing/$hash',
  getParentRoute: () => rootRoute,
} as any)

const SettingsCreditsRoute = SettingsCreditsImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => rootRoute,
} as any)

const LobbyIdRoute = LobbyIdImport.update({
  id: '/lobby/$id',
  path: '/lobby/$id',
  getParentRoute: () => rootRoute,
} as any)

const GameScoreRoute = GameScoreImport.update({
  id: '/game/score',
  path: '/game/score',
  getParentRoute: () => rootRoute,
} as any)

const SettingsVolumeIndexRoute = SettingsVolumeIndexImport.update({
  id: '/settings/volume/',
  path: '/settings/volume/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSongsIndexRoute = SettingsSongsIndexImport.update({
  id: '/settings/songs/',
  path: '/settings/songs/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsMicrophonesIndexRoute = SettingsMicrophonesIndexImport.update({
  id: '/settings/microphones/',
  path: '/settings/microphones/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsGeneralIndexRoute = SettingsGeneralIndexImport.update({
  id: '/settings/general/',
  path: '/settings/general/',
  getParentRoute: () => rootRoute,
} as any)

const PartyVersusIndexRoute = PartyVersusIndexImport.update({
  id: '/party/versus/',
  path: '/party/versus/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSongsPathRoute = SettingsSongsPathImport.update({
  id: '/settings/songs/$path',
  path: '/settings/songs/$path',
  getParentRoute: () => rootRoute,
} as any)

const SettingsMicrophonesIdRoute = SettingsMicrophonesIdImport.update({
  id: '/settings/microphones/$id',
  path: '/settings/microphones/$id',
  getParentRoute: () => rootRoute,
} as any)

const PartyVersusSettingsRoute = PartyVersusSettingsImport.update({
  id: '/party/versus/settings',
  path: '/party/versus/settings',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-lobby': {
      id: '/create-lobby'
      path: '/create-lobby'
      fullPath: '/create-lobby'
      preLoaderRoute: typeof CreateLobbyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingImport
      parentRoute: typeof rootRoute
    }
    '/game/score': {
      id: '/game/score'
      path: '/game/score'
      fullPath: '/game/score'
      preLoaderRoute: typeof GameScoreImport
      parentRoute: typeof rootRoute
    }
    '/lobby/$id': {
      id: '/lobby/$id'
      path: '/lobby/$id'
      fullPath: '/lobby/$id'
      preLoaderRoute: typeof LobbyIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/settings/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsImport
      parentRoute: typeof rootRoute
    }
    '/sing/$hash': {
      id: '/sing/$hash'
      path: '/sing/$hash'
      fullPath: '/sing/$hash'
      preLoaderRoute: typeof SingHashImport
      parentRoute: typeof rootRoute
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameIndexImport
      parentRoute: typeof rootRoute
    }
    '/lobby/': {
      id: '/lobby/'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyIndexImport
      parentRoute: typeof rootRoute
    }
    '/party/': {
      id: '/party/'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sing/': {
      id: '/sing/'
      path: '/sing'
      fullPath: '/sing'
      preLoaderRoute: typeof SingIndexImport
      parentRoute: typeof rootRoute
    }
    '/party/versus/settings': {
      id: '/party/versus/settings'
      path: '/party/versus/settings'
      fullPath: '/party/versus/settings'
      preLoaderRoute: typeof PartyVersusSettingsImport
      parentRoute: typeof rootRoute
    }
    '/settings/microphones/$id': {
      id: '/settings/microphones/$id'
      path: '/settings/microphones/$id'
      fullPath: '/settings/microphones/$id'
      preLoaderRoute: typeof SettingsMicrophonesIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/songs/$path': {
      id: '/settings/songs/$path'
      path: '/settings/songs/$path'
      fullPath: '/settings/songs/$path'
      preLoaderRoute: typeof SettingsSongsPathImport
      parentRoute: typeof rootRoute
    }
    '/party/versus/': {
      id: '/party/versus/'
      path: '/party/versus'
      fullPath: '/party/versus'
      preLoaderRoute: typeof PartyVersusIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/general/': {
      id: '/settings/general/'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/microphones/': {
      id: '/settings/microphones/'
      path: '/settings/microphones'
      fullPath: '/settings/microphones'
      preLoaderRoute: typeof SettingsMicrophonesIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/songs/': {
      id: '/settings/songs/'
      path: '/settings/songs'
      fullPath: '/settings/songs'
      preLoaderRoute: typeof SettingsSongsIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/volume/': {
      id: '/settings/volume/'
      path: '/settings/volume'
      fullPath: '/settings/volume'
      preLoaderRoute: typeof SettingsVolumeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-lobby': typeof CreateLobbyRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/game/score': typeof GameScoreRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/sing/$hash': typeof SingHashRoute
  '/game': typeof GameIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/party': typeof PartyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sing': typeof SingIndexRoute
  '/party/versus/settings': typeof PartyVersusSettingsRoute
  '/settings/microphones/$id': typeof SettingsMicrophonesIdRoute
  '/settings/songs/$path': typeof SettingsSongsPathRoute
  '/party/versus': typeof PartyVersusIndexRoute
  '/settings/general': typeof SettingsGeneralIndexRoute
  '/settings/microphones': typeof SettingsMicrophonesIndexRoute
  '/settings/songs': typeof SettingsSongsIndexRoute
  '/settings/volume': typeof SettingsVolumeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-lobby': typeof CreateLobbyRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/game/score': typeof GameScoreRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/sing/$hash': typeof SingHashRoute
  '/game': typeof GameIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/party': typeof PartyIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sing': typeof SingIndexRoute
  '/party/versus/settings': typeof PartyVersusSettingsRoute
  '/settings/microphones/$id': typeof SettingsMicrophonesIdRoute
  '/settings/songs/$path': typeof SettingsSongsPathRoute
  '/party/versus': typeof PartyVersusIndexRoute
  '/settings/general': typeof SettingsGeneralIndexRoute
  '/settings/microphones': typeof SettingsMicrophonesIndexRoute
  '/settings/songs': typeof SettingsSongsIndexRoute
  '/settings/volume': typeof SettingsVolumeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-lobby': typeof CreateLobbyRoute
  '/home': typeof HomeRoute
  '/loading': typeof LoadingRoute
  '/game/score': typeof GameScoreRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/sing/$hash': typeof SingHashRoute
  '/game/': typeof GameIndexRoute
  '/lobby/': typeof LobbyIndexRoute
  '/party/': typeof PartyIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sing/': typeof SingIndexRoute
  '/party/versus/settings': typeof PartyVersusSettingsRoute
  '/settings/microphones/$id': typeof SettingsMicrophonesIdRoute
  '/settings/songs/$path': typeof SettingsSongsPathRoute
  '/party/versus/': typeof PartyVersusIndexRoute
  '/settings/general/': typeof SettingsGeneralIndexRoute
  '/settings/microphones/': typeof SettingsMicrophonesIndexRoute
  '/settings/songs/': typeof SettingsSongsIndexRoute
  '/settings/volume/': typeof SettingsVolumeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-lobby'
    | '/home'
    | '/loading'
    | '/game/score'
    | '/lobby/$id'
    | '/settings/credits'
    | '/sing/$hash'
    | '/game'
    | '/lobby'
    | '/party'
    | '/settings'
    | '/sing'
    | '/party/versus/settings'
    | '/settings/microphones/$id'
    | '/settings/songs/$path'
    | '/party/versus'
    | '/settings/general'
    | '/settings/microphones'
    | '/settings/songs'
    | '/settings/volume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-lobby'
    | '/home'
    | '/loading'
    | '/game/score'
    | '/lobby/$id'
    | '/settings/credits'
    | '/sing/$hash'
    | '/game'
    | '/lobby'
    | '/party'
    | '/settings'
    | '/sing'
    | '/party/versus/settings'
    | '/settings/microphones/$id'
    | '/settings/songs/$path'
    | '/party/versus'
    | '/settings/general'
    | '/settings/microphones'
    | '/settings/songs'
    | '/settings/volume'
  id:
    | '__root__'
    | '/'
    | '/create-lobby'
    | '/home'
    | '/loading'
    | '/game/score'
    | '/lobby/$id'
    | '/settings/credits'
    | '/sing/$hash'
    | '/game/'
    | '/lobby/'
    | '/party/'
    | '/settings/'
    | '/sing/'
    | '/party/versus/settings'
    | '/settings/microphones/$id'
    | '/settings/songs/$path'
    | '/party/versus/'
    | '/settings/general/'
    | '/settings/microphones/'
    | '/settings/songs/'
    | '/settings/volume/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateLobbyRoute: typeof CreateLobbyRoute
  HomeRoute: typeof HomeRoute
  LoadingRoute: typeof LoadingRoute
  GameScoreRoute: typeof GameScoreRoute
  LobbyIdRoute: typeof LobbyIdRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SingHashRoute: typeof SingHashRoute
  GameIndexRoute: typeof GameIndexRoute
  LobbyIndexRoute: typeof LobbyIndexRoute
  PartyIndexRoute: typeof PartyIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SingIndexRoute: typeof SingIndexRoute
  PartyVersusSettingsRoute: typeof PartyVersusSettingsRoute
  SettingsMicrophonesIdRoute: typeof SettingsMicrophonesIdRoute
  SettingsSongsPathRoute: typeof SettingsSongsPathRoute
  PartyVersusIndexRoute: typeof PartyVersusIndexRoute
  SettingsGeneralIndexRoute: typeof SettingsGeneralIndexRoute
  SettingsMicrophonesIndexRoute: typeof SettingsMicrophonesIndexRoute
  SettingsSongsIndexRoute: typeof SettingsSongsIndexRoute
  SettingsVolumeIndexRoute: typeof SettingsVolumeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateLobbyRoute: CreateLobbyRoute,
  HomeRoute: HomeRoute,
  LoadingRoute: LoadingRoute,
  GameScoreRoute: GameScoreRoute,
  LobbyIdRoute: LobbyIdRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SingHashRoute: SingHashRoute,
  GameIndexRoute: GameIndexRoute,
  LobbyIndexRoute: LobbyIndexRoute,
  PartyIndexRoute: PartyIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SingIndexRoute: SingIndexRoute,
  PartyVersusSettingsRoute: PartyVersusSettingsRoute,
  SettingsMicrophonesIdRoute: SettingsMicrophonesIdRoute,
  SettingsSongsPathRoute: SettingsSongsPathRoute,
  PartyVersusIndexRoute: PartyVersusIndexRoute,
  SettingsGeneralIndexRoute: SettingsGeneralIndexRoute,
  SettingsMicrophonesIndexRoute: SettingsMicrophonesIndexRoute,
  SettingsSongsIndexRoute: SettingsSongsIndexRoute,
  SettingsVolumeIndexRoute: SettingsVolumeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-lobby",
        "/home",
        "/loading",
        "/game/score",
        "/lobby/$id",
        "/settings/credits",
        "/sing/$hash",
        "/game/",
        "/lobby/",
        "/party/",
        "/settings/",
        "/sing/",
        "/party/versus/settings",
        "/settings/microphones/$id",
        "/settings/songs/$path",
        "/party/versus/",
        "/settings/general/",
        "/settings/microphones/",
        "/settings/songs/",
        "/settings/volume/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-lobby": {
      "filePath": "create-lobby.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/loading": {
      "filePath": "loading.tsx"
    },
    "/game/score": {
      "filePath": "game/score.tsx"
    },
    "/lobby/$id": {
      "filePath": "lobby/$id.tsx"
    },
    "/settings/credits": {
      "filePath": "settings/credits.tsx"
    },
    "/sing/$hash": {
      "filePath": "sing/$hash.tsx"
    },
    "/game/": {
      "filePath": "game/index.tsx"
    },
    "/lobby/": {
      "filePath": "lobby/index.tsx"
    },
    "/party/": {
      "filePath": "party/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/sing/": {
      "filePath": "sing/index.tsx"
    },
    "/party/versus/settings": {
      "filePath": "party/versus/settings.tsx"
    },
    "/settings/microphones/$id": {
      "filePath": "settings/microphones/$id.tsx"
    },
    "/settings/songs/$path": {
      "filePath": "settings/songs/$path.tsx"
    },
    "/party/versus/": {
      "filePath": "party/versus/index.tsx"
    },
    "/settings/general/": {
      "filePath": "settings/general/index.tsx"
    },
    "/settings/microphones/": {
      "filePath": "settings/microphones/index.tsx"
    },
    "/settings/songs/": {
      "filePath": "settings/songs/index.tsx"
    },
    "/settings/volume/": {
      "filePath": "settings/volume/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
