{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tuneperfect.fullname" . }}-coturn-config
  namespace: {{ .Release.Namespace }}
data:
  STUN_URL: {{ .Values.coturn.stunUrl | quote }}
  TURN_URLS: {{ include "tuneperfect.coturn.turnUrls" . | quote }}
  TURN_CREDENTIAL_TTL: {{ .Values.coturn.credentialTtl | int | toString | quote }}
{{- end }}
