apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tuneperfect.fullname" . }}-postgresql-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tuneperfect.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  annotations:
    "helm.sh/resource-policy": keep
    longhorn.io/backup: "true"
    longhorn.io/recurring-backup-job: backup-daily
    longhorn.io/recurring-backup-retain: "7"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size | default "1Gi" }}