// Generated from the Rust types in `native/src` by `bun run native:types`. Don't edit.
// This file has been generated by Specta. Do not edit this file manually.
export type AppError = { type: "IoError"; data: string } | { type: "LoftyError"; data: string } | { type: "RecorderError"; data: string } | { type: "ProcessorError"; data: string } | { type: "CpalError"; data: string } | { type: "UltrastarError"; data: string } | { type: "UsdbError"; data: string };

export type LocalSong = {
	audioUrl: string | null,
	instrumentalUrl: string | null,
	videoUrl: string | null,
	coverUrl: string | null,
	backgroundUrl: string | null,
	replayGainTrackGain: number | null,
	replayGainTrackPeak: number | null,
	createdAt: number | null,
	/**
	 *  Number of voices (2+ for duets). A scanned library carries its voices packed (see
	 *  `packed_notes`) and leaves `voices` empty, so this is what lists and filters read.
	 */
	voiceCount: number,
} & Song;

export type Microphone = {
	/**
	 *  Stable device ID (cpal `DeviceId` serialized via `Display`). Preferred for
	 *  persisting a mic selection. `None` if the backend can't report an ID.
	 */
	id: string | null,
	name: string,
	channels: number,
};

/**  Configuration options for a microphone input */
export type MicrophoneOptions = {
	/**
	 *  Stable device ID (cpal `DeviceId`, serialized via `Display`). Preferred
	 *  for matching. `None` for configs saved before ID support was added, which
	 *  fall back to matching by `name`.
	 */
	deviceId?: string | null,
	/**
	 *  Human-readable device name. Used for display and as a fallback match when
	 *  `device_id` is absent or the device's ID can't be read.
	 */
	name: string,
	channel: number,
	gain: number | null,
	threshold: number | null,
	/**
	 *  Input latency in ms. The pitch window ends this far in the past so the
	 *  detected pitch matches the audio sung for the current beat.
	 */
	delay: number | null,
};

export type Note = {
	type: NoteType,
	startBeat: number,
	length: number,
	text: string,
	txtPitch: number,
	midiNote: number,
};

export type NoteType = "Normal" | "Golden" | "Freestyle" | "Rap" | "RapGolden";

/**
 *  Reported while parsing, in order: one `Start`, then `Progress` with the number of files done
 *  so far. Progress is throttled (see `PROGRESS_INTERVAL`); the last file is always reported.
 */
export type ParseEvent = { type: "start"; total: number } | { type: "progress"; song: string; done: number };

export type Phrase = {
	disappearBeat: number,
	notes: Note[],
};

export type Song = {
	title: string,
	artist: string,
	bpm: number | null,
	gap: number | null,
	videoGap: number | null,
	start: number | null,
	end: number | null,
	hash: string,
	album: string | null,
	language: string[] | null,
	edition: string[] | null,
	genre: string[] | null,
	year: number | null,
	creator: string[] | null,
	relative: boolean | null,
	audio: string | null,
	instrumental: string | null,
	cover: string | null,
	video: string | null,
	background: string | null,
	p1: string | null,
	p2: string | null,
	previewStart: number | null,
	version: string | null,
	tags: string[] | null,
	medleyStartBeat: number | null,
	medleyEndBeat: number | null,
	medleyStart: number | null,
	medleyEnd: number | null,
	voices: Voice[],
};

export type SongGroup = {
	path: string,
	songs: LocalSong[],
};

/**  Lightweight entry from USDB search results (no note data). */
export type UsdbSearchEntry = {
	songId: number,
	artist: string,
	title: string,
	genre: string,
	year: number | null,
	language: string,
	creator: string,
	edition: string,
	goldenNotes: boolean,
	rating: number | null,
	views: number,
	coverUrl: string | null,
	sampleUrl: string | null,
	/**  Unix timestamp from USDB's `data-lastchange` attribute. */
	usdbMtime: number,
};

/**  Full USDB song with parsed note data, ready for gameplay. */
export type UsdbSong = {
	songId: number,
	/**  YouTube ID for audio playback (from `a=` tag). Notes/GAP are timed to this. */
	audioYoutubeId: string | null,
	/**  YouTube ID for video (from `v=` tag). Shown as visual, muted if separate audio exists. */
	videoYoutubeId: string | null,
	coverUrl: string | null,
} & Song;

/**  Preview info for the search UI (YouTube ID, BPM, etc. — no note data). */
export type UsdbSongPreview = {
	song: UsdbSearchEntry,
	youtubeId: string | null,
	videoUrl: string | null,
	bpm: number | null,
	gap: number | null,
};

/**  Reported after each catalog page is fetched so the UI can show sync progress. */
export type UsdbSyncProgressEvent = {
	fetched: number,
	total: number,
};

export type Voice = {
	phrases: Phrase[],
};
