name: Build and update draft release

on:
  release:
    types: [created]

jobs:
  build-api:
    name: Build API Image
    if: github.event.release.draft == true
    uses: ./.github/workflows/docker-build-api.yaml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  build-web:
    name: Build Web Image
    if: github.event.release.draft == true
    uses: ./.github/workflows/docker-build-web.yaml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  build-app:
    name: Build App Image
    if: github.event.release.draft == true
    uses: ./.github/workflows/docker-build-app.yaml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  build-game:
    name: Build Game
    if: github.event.release.draft == true
    uses: ./.github/workflows/tauri-build-game.yaml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit

  update-draft-release:
    name: Update Draft Release
    if: github.event.release.draft == true
    runs-on: ubuntu-latest
    needs: [build-api, build-web, build-app, build-game]
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Game Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: tuneperfect-*

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          writeToFile: false

      - name: Update Draft Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.tag_name }}
          draft: true
          body: ${{ steps.changelog.outputs.changes }}
          files: artifacts/**/*
          fail_on_unmatched_files: false
