name: Publish and deploy release

on:
  release:
    types: [published]

jobs:
  deploy-to-cluster:
    name: Deploy to Kubernetes
    uses: ./.github/workflows/deploy-kubernetes.yaml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit 