name: Build and Deploy TunePerfect Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true

  build-api:
    name: Build API Image
    needs: create-draft-release
    uses: ./.github/workflows/docker-build-api.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-web:
    name: Build Web Image
    needs: create-draft-release
    uses: ./.github/workflows/docker-build-web.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-app:
    name: Build App Image
    needs: create-draft-release
    uses: ./.github/workflows/docker-build-app.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  build-game:
    name: Build Game
    needs: create-draft-release
    uses: ./.github/workflows/tauri-build-game.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  deploy-to-cluster:
    name: Deploy to Kubernetes
    needs: [build-api, build-web, build-app, build-game]
    uses: ./.github/workflows/deploy-kubernetes.yaml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [deploy-to-cluster]
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Game Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: tuneperfect-*

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          files: artifacts/**/*
          fail_on_unmatched_files: false
